[package]
name = "curvegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
assert_float_eq = "1.1.3"
resvg = "0.40.0"
svg = "0.16.0"
